### ISSUE TITLE
Grammar railroad diagram

### ISSUE THREAD

**Issue by mingodad** [fab4100/tree-sitter-ispc#1]
Here https://github.com/ispc/ispc/issues/2528#issue-1718399207 I did a railroad diagram from the parser grammar and here https://meimporta.eu/tree-sitter/json2ebnf.html we/you can have a railroad diagram from this project using https://raw.githubusercontent.com/fab4100/tree-sitter-ispc/master/src/grammar.json and then compare then to check if they match or help develop improve both.

Cheers !

**Comment by fab4100** [comment]
This is great! Thank you
