### ISSUE TITLE
Consider moving the repo to `tree-sitter-grammars`

### ISSUE THREAD

**Issue by amaanq** [fab4100/tree-sitter-ispc#5]
Hey @fab4100, I hope you've been well. We at nvim-treesitter (and potentially more folks from other teams interested in an ecosystem-wide effort to maintain grammars) have decided to move all of our own grammars collectively into one org, to make it easier for us all to fix bugs or keep things up to date (scanner crashes, regenerating with the latest abi, etc.) without having to rely on one sole maintainer (you).

This is 100% optional, and please don't feel pressured or feel like you have an obligation of moving the grammar to the org, but it will help everyone a lot, us at nvim-treesitter, other users downstream, to know that a grammar won't ever die should a maintainer call it quits or go MIA. We also have org-wide actions that we maintain (out of sight, out of mind for you) and a grammar template (soon for newbies) in place to ensure authors have a better experience with working on and fixing tree-sitter grammars. It also enables anyone looking to find grammars for a specific language to only have to search in one spot

Our org is here: https://github.com/tree-sitter-grammars

If you want to participate (and don't worry, you'll still have full write perms to your repo, just no admin access), that'd be great! All you have to do is transfer the repo to me in the repository settings and I'll handle it from there. Thanks a lot, and again no worries if the answer is no!

**Comment by fab4100** [comment]
This sounds good!  I cannot transfer ownership because a fork exists in your repositories.

**Comment by amaanq** [comment]
I deleted it, try now?

**Comment by fab4100** [comment]
Should be OK now.  Will you eventually do a collective pull request in https://tree-sitter.github.io/tree-sitter/ to update the new parser locations?

**Comment by amaanq** [comment]
yes we will in a bit, but old links redirect to the new one on github anyways :) so it's ok for a few days

**Comment by fab4100** [comment]
Perfect! Thanks for the initiative.  Would be nice if this moves beyond nvim-treesitter eventually.

**Comment by amaanq** [comment]
Thank you! I've just moved it over now, you should have write access to https://github.com/tree-sitter-grammars/tree-sitter-ispc but if not let me know!
